### ISSUE TITLE
Drag and drop an anchor tag navigates to link on Firefox

### ISSUE THREAD

**Issue by gasperno** [sirctseb/assortment#3]
Hi @sirctseb 
I noticed an issues with this code. I came across this issue when I was using your library. 

When I have anchor tags inside a div id="container". If I am dragging and dropping links. After drop, page navigates to href in the anchor element which is dropped. 
I found a fix too.

Are you accepting PRs for this project? 

Thanks,
Harsha.

**Comment by sirctseb** [comment]
Hi Harsha,
Absolutely. Put in the PR and I will pull in after a hasty review.

**Comment by gasperno** [comment]
Hi @sirctseb, 
Thank you for quick response. Here is the [link](https://github.com/sirctseb/assortment/pull/4) for pull request.

There is an addition and deletion. I added comments at each modification.
I would really appreciate if you can push and publish if it is acceptable to you.

**Comment by sirctseb** [comment]
version 0.1.4 now on pub. thanks!
